[package]
name = "wasmer/wcgi-wordpress-demo"
version = "0.1.6"
description = "A PHP Wordpress template for WCGI applications"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/wasmerio/wcgi-wordpress-demo"

[[module]]
name = "php"
source = "php-cgi.wasm"
abi = "wasi"

[[command]]
name = "php"
runner = "wcgi"
module = "php"

[command.annotations]
wcgi = { dialect = "rfc-3875" }
wasi = { atom = "php", env = ["SCRIPT_FILENAME=/app/app.php", "DOCUMENT_ROOT=/app/"] }

[fs]
"app" = "app"
