<?php
 
return array (
    'header1' =>
        array (
            'index' => 0,
            'id' => 'header_preset_0',
            'thumb' => '//extendthemes.com/assets/mesmerize/previews/headers/header1.jpg',
            'preview' => '//extendthemes.com/assets/mesmerize/previews/headers/header1.jpg',
            'description' => 'header preset 1',
            'settings' =>
                array (
                    'header_text' => '1',
                    'header_textcolor' => '',
                    'header_video' => '',
                    'external_header_video' => '',
                    'header_image' => '[tag_theme_uri]/assets/images/headers/home_page_header.jpg',
                    'header_image_data' => '',
                    'header_presets' => '',
                    'frontpage_header_presets_pro' => '',
                    'header_offscreen_nav_on_tablet' => '0',
                    'header_offscreen_nav_on_desktop' => '0',
                    'header_background_type' => 'image',
                    'header_bg_options_group_button' => '',
                    'header_bg_color' => '#6a73da',
                    'header_front_page_image' => '[tag_theme_uri]/assets/images/headers/home_page_header.jpg',
                    'header_parallax_pro' => '',
                    'header_bg_position' => 'center center',
                    'header_parallax' => '1',
                    'header_front_page_image_mobile' => '',
                    'header_bg_position_mobile' => '50%',
                    'header_bg_position_mobile_offset' => '0',
                    'header_slideshow' =>
                        array (
                            0 =>
                                array (
                                    'url' => '[tag_theme_uri]/assets/images/slideshow_slide1.jpg',
                                ),
                            1 =>
                                array (
                                    'url' => '[tag_theme_uri]/assets/images/slideshow_slide2.jpg',
                                ),
                        ),
                    'header_slideshow_duration' => '5000',
                    'header_slideshow_speed' => '1000',
                    'header_video_external' => 'https://www.youtube.com/watch?v=3iXYciBTQ0c',
                    'header_video_poster' => '[tag_theme_uri]/assets/images/video-poster.jpg',
                    'header_gradient' => 'plum_plate',
                    'header_show_overlay' => '1',
                    'header_overlay_type' => 'gradient',
                    'header_overlay_options_group_button' => '',
                    'header_overlay_color' => '#ffffff',
                    'header_overlay_opacity' => '0.5',
                    'header_overlay_gradient_colors' => '{"angle":"142","colors":[{"color":"rgba(244, 59, 71, 0.8)","position":"0%"},{"color":"rgba(69, 58, 148, 0.8)","position":"100%"}]}',
                    'header_overlay_shape' => 'none',
                    'header_overlay_shape_light' => '0',
                    'header_show_bottom_arrow' => '0',
                    'header_bottom_arrow_options_group_button' => '',
                    'header_bounce_bottom_arrow' => '1',
                    'header_bottom_arrow' => 'fa-angle-down',
                    'header_size_bottom_arrow' => '50',
                    'header_offset_bottom_arrow' => '20',
                    'header_color_bottom_arrow' => '#ffffff',
                    'header_background_bottom_arrow' => 'rgba(255,255,255,0)',
                    'full_height_header' => '0',
                    'header_overlap' => '1',
                    'header_overlap_with' => '95px',
                    'header_show_separator' => '0',
                    'header_options_separator_group_button' => '',
                    'header_separator' => 'mesmerize/1.wave-and-line',
                    'header_separator_color' => '#ffffff',
                    'header_separator_color_accent' => '#ff8c00',
                    'header_separator_height' => '154',
                    'header_content_show_title' => '1',
                    'header_content_title_group' => '',
                    'header_title' => 'Probably the best multipurpose theme on WordPress.org',
                    'header_content_show_subtitle' => '1',
                    'header_content_subtitle_group' => '',
                    'header_subtitle' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
                    'header_content_show_buttons' => '1',
                    'header_content_buttons_group' => '',
                    'header_content_buttons' =>
                        array (
                            0 =>
                                array (
                                    'label' => 'GET STARTED TODAY',
                                    'url' => '#',
                                    'target' => '_self',
                                    'class' => 'big button color1 round',
                                ),
                            1 =>
                                array (
                                    'label' => 'LEARN MORE',
                                    'url' => '#',
                                    'target' => '_self',
                                    'class' => 'button big white round outline',
                                ),
                        ),
                    'header_content_partial' => 'media-on-right',
                    'header_content_media' => 'image',
                    'header_spacing' =>
                        array (
                            'top' => '5%',
                            'bottom' => '8%',
                        ),
                    'header_spacing_mobile' =>
                        array (
                            'top' => '10%',
                            'bottom' => '10%',
                        ),
                    'header_text_box_settings' => '',
                    'header_text_box_text_align' => 'left',
                    'header_text_box_text_width' => '80',
                    'header_text_box_text_vertical_align' => 'middle-sm',
                    'header_media_box_settings' => '',
                    'header_media_box_top_bottom_width' => '50',
                    'header_media_box_vertical_align' => 'middle-sm',
                    'header_content_image' => '[tag_theme_uri]/assets/images/headers/media-image-default.jpg',
                    'header_column_width' => '29',
                    'header_content_media_spacing' =>
                        array (
                            'top' => '0px',
                            'bottom' => '0px',
                        ),
                    'header_content_frame_type' => 'border',
                    'header_content_frame_width' => '100',
                    'header_content_frame_height' => '100',
                    'header_content_frame_offset_left' => '-13',
                    'header_content_frame_offset_top' => '10',
                    'header_content_frame_thickness' => '11',
                    'header_content_frame_color' => 'rgba(255,255,255,0.726)',
                    'header_content_frame_show_over_image' => '0',
                    'header_content_frame_shadow' => '1',
                    'enable_top_bar' => '1',
                    'header_top_bar_area-left_content' => 'info',
                    'header_top_bar_area-left_info_field_0_enabled' => '1',
                    'header_top_bar_area-left_info_field_0_icon' => 'fa-map-marker',
                    'header_top_bar_area-left_info_field_0_text' => 'Location,TX 75035,USA',
                    'header_top_bar_area-left_info_field_1_enabled' => '1',
                    'header_top_bar_area-left_info_field_1_icon' => 'fa-phone',
                    'header_top_bar_area-left_info_field_1_text' => '+1234567890',
                    'header_top_bar_area-left_info_field_2_enabled' => '1',
                    'header_top_bar_area-left_info_field_2_icon' => 'fa-envelope',
                    'header_top_bar_area-left_info_field_2_text' => 'info@yourmail.com',
                    'header_top_bar_area-left_info_fields_group_button' => '',
                    'header_top_bar_area-left_social_icon_0_enabled' => '1',
                    'header_top_bar_area-left_social_icon_0_icon' => 'fa-facebook-official',
                    'header_top_bar_area-left_social_icon_0_link' => 'https://facebook.com',
                    'header_top_bar_area-left_social_icon_1_enabled' => '1',
                    'header_top_bar_area-left_social_icon_1_icon' => 'fa-twitter-square',
                    'header_top_bar_area-left_social_icon_1_link' => 'https://twitter.com',
                    'header_top_bar_area-left_social_icon_2_enabled' => '1',
                    'header_top_bar_area-left_social_icon_2_icon' => 'fa-instagram',
                    'header_top_bar_area-left_social_icon_2_link' => 'https://instagram.com',
                    'header_top_bar_area-left_social_icon_3_enabled' => '1',
                    'header_top_bar_area-left_social_icon_3_icon' => 'fa-google-plus-square',
                    'header_top_bar_area-left_social_icon_3_link' => 'https://plus.google.com',
                    'header_top_bar_area-left_social_icons_group_button' => '',
                    'header_top_bar_area-right_content' => 'social',
                    'header_top_bar_area-right_info_field_0_enabled' => '1',
                    'header_top_bar_area-right_info_field_0_icon' => 'fa-map-marker',
                    'header_top_bar_area-right_info_field_0_text' => 'Location,TX 75035,USA',
                    'header_top_bar_area-right_info_field_1_enabled' => '1',
                    'header_top_bar_area-right_info_field_1_icon' => 'fa-phone',
                    'header_top_bar_area-right_info_field_1_text' => '+1234567890',
                    'header_top_bar_area-right_info_field_2_enabled' => '1',
                    'header_top_bar_area-right_info_field_2_icon' => 'fa-envelope',
                    'header_top_bar_area-right_info_field_2_text' => 'info@yourmail.com',
                    'header_top_bar_area-right_info_fields_group_button' => '',
                    'header_top_bar_area-right_social_icon_0_enabled' => '1',
                    'header_top_bar_area-right_social_icon_0_icon' => 'fa-facebook-official',
                    'header_top_bar_area-right_social_icon_0_link' => 'https://facebook.com',
                    'header_top_bar_area-right_social_icon_1_enabled' => '1',
                    'header_top_bar_area-right_social_icon_1_icon' => 'fa-twitter-square',
                    'header_top_bar_area-right_social_icon_1_link' => 'https://twitter.com',
                    'header_top_bar_area-right_social_icon_2_enabled' => '1',
                    'header_top_bar_area-right_social_icon_2_icon' => 'fa-instagram',
                    'header_top_bar_area-right_social_icon_2_link' => 'https://instagram.com',
                    'header_top_bar_area-right_social_icon_3_enabled' => '1',
                    'header_top_bar_area-right_social_icon_3_icon' => 'fa-google-plus-square',
                    'header_top_bar_area-right_social_icon_3_link' => 'https://plus.google.com',
                    'header_top_bar_area-right_social_icons_group_button' => '',
                    'header_nav_sticked' => '1',
                    'header_nav_boxed' => '0',
                    'header_nav_border' => '0',
                    'header_nav_border_color' => 'rgba(255, 255, 255, 1)',
                    'header_nav_border_thickness' => '2',
                    'header_nav_border_group_button' => '',
                    'header_nav_transparent' => '0',
                    'header_nav_use_dark_logo' => '0',
                    'header_nav_bar_type' => 'default',
                    'header_nav_style' => 'active-line-bottom',
                    'header_overlappable_section' => 'overlappable-4',
                    'one_page_express_header_image' => '[tag_theme_uri]/assets/images/home_page_header.jpg',
                ),
        ),
    'header2' =>
        array (
            'index' => 1,
            'id' => 'header_preset_1',
            'thumb' => '//extendthemes.com/assets/mesmerize/previews/headers/header2.jpg',
            'preview' => '//extendthemes.com/assets/mesmerize/previews/headers/header2.jpg',
            'description' => 'header preset 2',
            'settings' =>
                array (
                    'header_text' => '1',
                    'header_textcolor' => '',
                    'header_video' => '',
                    'external_header_video' => '',
                    'header_image' => '[tag_theme_uri]/assets/images/headers/home_page_header.jpg',
                    'header_image_data' => '',
                    'header_presets' => '',
                    'frontpage_header_presets_pro' => '',
                    'header_offscreen_nav_on_tablet' => '0',
                    'header_offscreen_nav_on_desktop' => '0',
                    'header_background_type' => 'video',
                    'header_bg_options_group_button' => '',
                    'header_bg_color' => '#6a73da',
                    'header_front_page_image' => '[tag_theme_uri]/assets/images/headers/home_page_header.jpg',
                    'header_parallax_pro' => '',
                    'header_bg_position' => 'center center',
                    'header_parallax' => '1',
                    'header_front_page_image_mobile' => '',
                    'header_bg_position_mobile' => '50%',
                    'header_bg_position_mobile_offset' => '0',
                    'header_slideshow' =>
                        array (
                            0 =>
                                array (
                                    'url' => '[tag_theme_uri]/assets/images/slideshow_slide1.jpg',
                                ),
                            1 =>
                                array (
                                    'url' => '[tag_theme_uri]/assets/images/slideshow_slide2.jpg',
                                ),
                        ),
                    'header_slideshow_duration' => '5000',
                    'header_slideshow_speed' => '1000',
                    'header_video_external' => 'https://www.youtube.com/watch?v=3iXYciBTQ0c',
                    'header_video_poster' => '[tag_theme_uri]/assets/images/video-poster.jpg',
                    'header_gradient' => 'plum_plate',
                    'header_show_overlay' => '1',
                    'header_overlay_type' => 'gradient',
                    'header_overlay_options_group_button' => '',
                    'header_overlay_color' => '#2D0474',
                    'header_overlay_opacity' => '0.5',
                    'header_overlay_gradient_colors' => '{"angle":"135","colors":[{"color":"rgba(102, 126, 234, 0.8)","position":"0%"},{"color":"rgba(118, 75, 162, 0.8)","position":"100%"}]}',
                    'header_overlay_shape' => 'none',
                    'header_overlay_shape_light' => '0',
                    'header_show_bottom_arrow' => '0',
                    'header_bottom_arrow_options_group_button' => '',
                    'header_bounce_bottom_arrow' => '1',
                    'header_bottom_arrow' => 'fa-angle-down',
                    'header_size_bottom_arrow' => '50',
                    'header_offset_bottom_arrow' => '20',
                    'header_color_bottom_arrow' => '#ffffff',
                    'header_background_bottom_arrow' => 'rgba(255,255,255,0)',
                    'full_height_header' => '0',
                    'header_overlap' => '0',
                    'header_overlap_with' => '200px',
                    'header_show_separator' => '1',
                    'header_options_separator_group_button' => '',
                    'header_separator' => 'mesmerize/1.wave-and-line',
                    'header_separator_color' => '#ffffff',
                    'header_separator_color_accent' => '#ff8c00',
                    'header_separator_height' => '178',
                    'header_content_show_title' => '1',
                    'header_content_title_group' => '',
                    'header_title' => 'If oportunity doesn\'t knock, build a door',
                    'header_content_show_subtitle' => '0',
                    'header_content_subtitle_group' => '',
                    'header_subtitle' => 'You can set this subtitle from the customizer.',
                    'header_content_show_buttons' => '1',
                    'header_content_buttons_group' => '',
                    'header_content_buttons' =>
                        array (
                            0 =>
                                array (
                                    'label' => 'GET STARTED TODAY',
                                    'url' => '#',
                                    'target' => '_self',
                                    'class' => 'button big color2 round',
                                ),
                            1 =>
                                array (
                                    'label' => 'LEARN MORE',
                                    'url' => '#',
                                    'target' => '_self',
                                    'class' => 'button big white round outline',
                                ),
                        ),
                    'header_content_partial' => 'content-on-center',
                    'header_content_media' => 'image',
                    'header_spacing' =>
                        array (
                            'top' => '12%',
                            'bottom' => '23%',
                        ),
                    'header_spacing_mobile' =>
                        array (
                            'top' => '10%',
                            'bottom' => '40%',
                        ),
                    'header_text_box_settings' => '',
                    'header_text_box_text_align' => 'center',
                    'header_text_box_text_width' => '70',
                    'header_text_box_text_vertical_align' => 'middle-sm',
                    'header_media_box_settings' => '',
                    'header_media_box_top_bottom_width' => '50',
                    'header_media_box_vertical_align' => 'middle-sm',
                    'header_content_image' => '[tag_theme_uri]/assets/images/headers/media-image-default.jpg',
                    'header_column_width' => '37',
                    'header_content_media_spacing' =>
                        array (
                            'top' => '0px',
                            'bottom' => '0px',
                        ),
                    'header_content_frame_type' => 'none',
                    'header_content_frame_width' => '100',
                    'header_content_frame_height' => '100',
                    'header_content_frame_offset_left' => '10',
                    'header_content_frame_offset_top' => '10',
                    'header_content_frame_thickness' => '10',
                    'header_content_frame_color' => 'rgba(0,0,0,0.5)',
                    'header_content_frame_show_over_image' => '0',
                    'header_content_frame_shadow' => '1',
                    'enable_top_bar' => '0',
                    'header_top_bar_area-left_content' => 'info',
                    'header_top_bar_area-left_info_field_0_enabled' => '1',
                    'header_top_bar_area-left_info_field_0_icon' => 'fa-map-marker',
                    'header_top_bar_area-left_info_field_0_text' => 'Location,TX 75035,USA',
                    'header_top_bar_area-left_info_field_1_enabled' => '1',
                    'header_top_bar_area-left_info_field_1_icon' => 'fa-phone',
                    'header_top_bar_area-left_info_field_1_text' => '+1234567890',
                    'header_top_bar_area-left_info_field_2_enabled' => '1',
                    'header_top_bar_area-left_info_field_2_icon' => 'fa-envelope',
                    'header_top_bar_area-left_info_field_2_text' => 'info@yourmail.com',
                    'header_top_bar_area-left_info_fields_group_button' => '',
                    'header_top_bar_area-left_social_icon_0_enabled' => '1',
                    'header_top_bar_area-left_social_icon_0_icon' => 'fa-facebook-official',
                    'header_top_bar_area-left_social_icon_0_link' => 'https://facebook.com',
                    'header_top_bar_area-left_social_icon_1_enabled' => '1',
                    'header_top_bar_area-left_social_icon_1_icon' => 'fa-twitter-square',
                    'header_top_bar_area-left_social_icon_1_link' => 'https://twitter.com',
                    'header_top_bar_area-left_social_icon_2_enabled' => '1',
                    'header_top_bar_area-left_social_icon_2_icon' => 'fa-instagram',
                    'header_top_bar_area-left_social_icon_2_link' => 'https://instagram.com',
                    'header_top_bar_area-left_social_icon_3_enabled' => '1',
                    'header_top_bar_area-left_social_icon_3_icon' => 'fa-google-plus-square',
                    'header_top_bar_area-left_social_icon_3_link' => 'https://plus.google.com',
                    'header_top_bar_area-left_social_icons_group_button' => '',
                    'header_top_bar_area-right_content' => 'social',
                    'header_top_bar_area-right_info_field_0_enabled' => '1',
                    'header_top_bar_area-right_info_field_0_icon' => 'fa-map-marker',
                    'header_top_bar_area-right_info_field_0_text' => 'Location,TX 75035,USA',
                    'header_top_bar_area-right_info_field_1_enabled' => '1',
                    'header_top_bar_area-right_info_field_1_icon' => 'fa-phone',
                    'header_top_bar_area-right_info_field_1_text' => '+1234567890',
                    'header_top_bar_area-right_info_field_2_enabled' => '1',
                    'header_top_bar_area-right_info_field_2_icon' => 'fa-envelope',
                    'header_top_bar_area-right_info_field_2_text' => 'info@yourmail.com',
                    'header_top_bar_area-right_info_fields_group_button' => '',
                    'header_top_bar_area-right_social_icon_0_enabled' => '1',
                    'header_top_bar_area-right_social_icon_0_icon' => 'fa-facebook-official',
                    'header_top_bar_area-right_social_icon_0_link' => 'https://facebook.com',
                    'header_top_bar_area-right_social_icon_1_enabled' => '1',
                    'header_top_bar_area-right_social_icon_1_icon' => 'fa-twitter-square',
                    'header_top_bar_area-right_social_icon_1_link' => 'https://twitter.com',
                    'header_top_bar_area-right_social_icon_2_enabled' => '1',
                    'header_top_bar_area-right_social_icon_2_icon' => 'fa-instagram',
                    'header_top_bar_area-right_social_icon_2_link' => 'https://instagram.com',
                    'header_top_bar_area-right_social_icon_3_enabled' => '1',
                    'header_top_bar_area-right_social_icon_3_icon' => 'fa-google-plus-square',
                    'header_top_bar_area-right_social_icon_3_link' => 'https://plus.google.com',
                    'header_top_bar_area-right_social_icons_group_button' => '',
                    'header_nav_sticked' => '1',
                    'header_nav_boxed' => '0',
                    'header_nav_border' => '0',
                    'header_nav_border_color' => 'rgba(255, 255, 255, 1)',
                    'header_nav_border_thickness' => '2',
                    'header_nav_border_group_button' => '',
                    'header_nav_transparent' => '1',
                    'header_nav_use_dark_logo' => '0',
                    'header_nav_bar_type' => 'logo-above-menu',
                    'header_nav_style' => 'active-line-bottom',
                    'one_page_express_header_image' => '[tag_theme_uri]/assets/images/home_page_header.jpg',
                ),
        ),
    'header3' =>
        array (
            'index' => 2,
            'id' => 'header_preset_2',
            'thumb' => '//extendthemes.com/assets/mesmerize/previews/headers/header3.jpg',
            'preview' => '//extendthemes.com/assets/mesmerize/previews/headers/header3.jpg',
            'description' => 'header preset 3',
            'settings' =>
                array (
                    'header_text' => '1',
                    'header_textcolor' => '',
                    'header_video' => '',
                    'external_header_video' => '',
                    'header_image' => '[tag_theme_uri]/assets/images/headers/home_page_header.jpg',
                    'header_image_data' => '',
                    'header_presets' => '',
                    'frontpage_header_presets_pro' => '',
                    'header_offscreen_nav_on_tablet' => '0',
                    'header_offscreen_nav_on_desktop' => '0',
                    'header_background_type' => 'gradient',
                    'header_bg_options_group_button' => '',
                    'header_bg_color' => '#6a73da',
                    'header_front_page_image' => '[tag_theme_uri]/assets/images/headers/home_page_header.jpg',
                    'header_parallax_pro' => '',
                    'header_bg_position' => 'center center',
                    'header_parallax' => '1',
                    'header_front_page_image_mobile' => '',
                    'header_bg_position_mobile' => '50%',
                    'header_bg_position_mobile_offset' => '0',
                    'header_slideshow' =>
                        array (
                            0 =>
                                array (
                                    'url' => '[tag_theme_uri]/assets/images/images/slideshow_slide1.jpg',
                                ),
                            1 =>
                                array (
                                    'url' => '[tag_theme_uri]/assets/images/slideshow_slide2.jpg',
                                ),
                        ),
                    'header_slideshow_duration' => '5000',
                    'header_slideshow_speed' => '1000',
                    'header_video_external' => 'https://www.youtube.com/watch?v=3iXYciBTQ0c',
                    'header_video_poster' => '[tag_theme_uri]/assets/images/video-poster.jpg',
                    'header_gradient' => 'plum_plate',
                    'header_show_overlay' => '1',
                    'header_overlay_type' => 'none',
                    'header_overlay_options_group_button' => '',
                    'header_overlay_color' => '#FFFFFF',
                    'header_overlay_opacity' => '0.5',
                    'header_overlay_gradient_colors' => '{"angle":"142","colors":[{"color":"rgba(244,59,71, 0.8)","position":"0%"},{"color":"rgba(69,58,148, 0.8)","position":"100%"}]}',
                    'header_overlay_shape' => 'circles',
                    'header_overlay_shape_light' => '0',
                    'header_show_bottom_arrow' => '0',
                    'header_bottom_arrow_options_group_button' => '',
                    'header_bounce_bottom_arrow' => '1',
                    'header_bottom_arrow' => 'fa-angle-down',
                    'header_size_bottom_arrow' => '50',
                    'header_offset_bottom_arrow' => '20',
                    'header_color_bottom_arrow' => '#ffffff',
                    'header_background_bottom_arrow' => 'rgba(255,255,255,0)',
                    'full_height_header' => '0',
                    'header_overlap' => '0',
                    'header_overlap_with' => '200px',
                    'header_show_separator' => '1',
                    'header_options_separator_group_button' => '',
                    'header_separator' => 'tilt-flipped',
                    'header_separator_color' => '#ffffff',
                    'header_separator_color_accent' => '#ff8c00',
                    'header_separator_height' => '154',
                    'header_content_show_title' => '1',
                    'header_content_title_group' => '',
                    'header_title' => 'If oportunity doesn\'t knock, build a door',
                    'header_content_show_subtitle' => '1',
                    'header_content_subtitle_group' => '',
                    'header_subtitle' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
                    'header_content_show_buttons' => '1',
                    'header_content_buttons_group' => '',
                    'header_content_buttons' =>
                        array (
                            0 =>
                                array (
                                    'label' => 'GET STARTED TODAY',
                                    'url' => '#',
                                    'target' => '_self',
                                    'class' => 'big button color2 round',
                                ),
                            1 =>
                                array (
                                    'label' => 'LEARN MORE',
                                    'url' => '#',
                                    'target' => '_self',
                                    'class' => 'button big white round outline',
                                ),
                        ),
                    'header_content_partial' => 'media-on-right',
                    'header_content_media' => 'image',
                    'header_spacing' =>
                        array (
                            'top' => '6%',
                            'bottom' => '4%',
                        ),
                    'header_spacing_mobile' =>
                        array (
                            'top' => '10%',
                            'bottom' => '10%',
                        ),
                    'header_text_box_settings' => '',
                    'header_text_box_text_align' => 'left',
                    'header_text_box_text_width' => '80',
                    'header_text_box_text_vertical_align' => 'middle-sm',
                    'header_media_box_settings' => '',
                    'header_media_box_top_bottom_width' => '50',
                    'header_media_box_vertical_align' => 'middle-sm',
                    'header_content_image' => '[tag_theme_uri]/assets/images/headers/media-image-default.jpg',
                    'header_column_width' => '29',
                    'header_content_media_spacing' =>
                        array (
                            'top' => '0px',
                            'bottom' => '0px',
                        ),
                    'header_content_frame_type' => 'background',
                    'header_content_frame_width' => '100',
                    'header_content_frame_height' => '100',
                    'header_content_frame_offset_left' => '-19',
                    'header_content_frame_offset_top' => '10',
                    'header_content_frame_thickness' => '10',
                    'header_content_frame_color' => 'rgb(255,174,30)',
                    'header_content_frame_show_over_image' => '0',
                    'header_content_frame_shadow' => '1',
                    'enable_top_bar' => '0',
                    'header_top_bar_area-left_content' => 'info',
                    'header_top_bar_area-left_info_field_0_enabled' => '1',
                    'header_top_bar_area-left_info_field_0_icon' => 'fa-map-marker',
                    'header_top_bar_area-left_info_field_0_text' => 'Location,TX 75035,USA',
                    'header_top_bar_area-left_info_field_1_enabled' => '1',
                    'header_top_bar_area-left_info_field_1_icon' => 'fa-phone',
                    'header_top_bar_area-left_info_field_1_text' => '+1234567890',
                    'header_top_bar_area-left_info_field_2_enabled' => '1',
                    'header_top_bar_area-left_info_field_2_icon' => 'fa-envelope',
                    'header_top_bar_area-left_info_field_2_text' => 'info@yourmail.com',
                    'header_top_bar_area-left_info_fields_group_button' => '',
                    'header_top_bar_area-left_social_icon_0_enabled' => '1',
                    'header_top_bar_area-left_social_icon_0_icon' => 'fa-facebook-official',
                    'header_top_bar_area-left_social_icon_0_link' => 'https://facebook.com',
                    'header_top_bar_area-left_social_icon_1_enabled' => '1',
                    'header_top_bar_area-left_social_icon_1_icon' => 'fa-twitter-square',
                    'header_top_bar_area-left_social_icon_1_link' => 'https://twitter.com',
                    'header_top_bar_area-left_social_icon_2_enabled' => '1',
                    'header_top_bar_area-left_social_icon_2_icon' => 'fa-instagram',
                    'header_top_bar_area-left_social_icon_2_link' => 'https://instagram.com',
                    'header_top_bar_area-left_social_icon_3_enabled' => '1',
                    'header_top_bar_area-left_social_icon_3_icon' => 'fa-google-plus-square',
                    'header_top_bar_area-left_social_icon_3_link' => 'https://plus.google.com',
                    'header_top_bar_area-left_social_icons_group_button' => '',
                    'header_top_bar_area-right_content' => 'social',
                    'header_top_bar_area-right_info_field_0_enabled' => '1',
                    'header_top_bar_area-right_info_field_0_icon' => 'fa-map-marker',
                    'header_top_bar_area-right_info_field_0_text' => 'Location,TX 75035,USA',
                    'header_top_bar_area-right_info_field_1_enabled' => '1',
                    'header_top_bar_area-right_info_field_1_icon' => 'fa-phone',
                    'header_top_bar_area-right_info_field_1_text' => '+1234567890',
                    'header_top_bar_area-right_info_field_2_enabled' => '1',
                    'header_top_bar_area-right_info_field_2_icon' => 'fa-envelope',
                    'header_top_bar_area-right_info_field_2_text' => 'info@yourmail.com',
                    'header_top_bar_area-right_info_fields_group_button' => '',
                    'header_top_bar_area-right_social_icon_0_enabled' => '1',
                    'header_top_bar_area-right_social_icon_0_icon' => 'fa-facebook-official',
                    'header_top_bar_area-right_social_icon_0_link' => 'https://facebook.com',
                    'header_top_bar_area-right_social_icon_1_enabled' => '1',
                    'header_top_bar_area-right_social_icon_1_icon' => 'fa-twitter-square',
                    'header_top_bar_area-right_social_icon_1_link' => 'https://twitter.com',
                    'header_top_bar_area-right_social_icon_2_enabled' => '1',
                    'header_top_bar_area-right_social_icon_2_icon' => 'fa-instagram',
                    'header_top_bar_area-right_social_icon_2_link' => 'https://instagram.com',
                    'header_top_bar_area-right_social_icon_3_enabled' => '1',
                    'header_top_bar_area-right_social_icon_3_icon' => 'fa-google-plus-square',
                    'header_top_bar_area-right_social_icon_3_link' => 'https://plus.google.com',
                    'header_top_bar_area-right_social_icons_group_button' => '',
                    'header_nav_sticked' => '1',
                    'header_nav_boxed' => '0',
                    'header_nav_border' => '0',
                    'header_nav_border_color' => 'rgba(255, 255, 255, 1)',
                    'header_nav_border_thickness' => '2',
                    'header_nav_border_group_button' => '',
                    'header_nav_transparent' => '1',
                    'header_nav_use_dark_logo' => '0',
                    'header_nav_bar_type' => 'default',
                    'header_nav_style' => 'active-line-bottom',
                    'one_page_express_header_image' => '[tag_theme_uri]/assets/images/home_page_header.jpg',
                ),
        ),
    'header4' =>
        array (
            'index' => 3,
            'id' => 'header_preset_3',
            'thumb' => '//extendthemes.com/assets/mesmerize/previews/headers/header4.jpg',
            'preview' => '//extendthemes.com/assets/mesmerize/previews/headers/header4.jpg',
            'description' => 'header preset 4',
            'settings' =>
                array (
                    'header_text' => '1',
                    'header_textcolor' => '',
                    'header_video' => '',
                    'external_header_video' => '',
                    'header_image' => '[tag_theme_uri]/assets/images/headers/home_page_header.jpg',
                    'header_image_data' => '',
                    'header_presets' => '',
                    'frontpage_header_presets_pro' => '',
                    'header_offscreen_nav_on_tablet' => '0',
                    'header_offscreen_nav_on_desktop' => '0',
                    'header_background_type' => 'image',
                    'header_bg_options_group_button' => '',
                    'header_bg_color' => '#6a73da',
                    'header_front_page_image' => '[tag_theme_uri]/assets/images/headers/pexels-photo-450276.jpg',
                    'header_parallax_pro' => '',
                    'header_bg_position' => 'center center',
                    'header_parallax' => '1',
                    'header_front_page_image_mobile' => '[tag_theme_uri]/assets/images/headers/pexels-photo-450276-mobile.jpg',
                    'header_bg_position_mobile' => '50%',
                    'header_bg_position_mobile_offset' => '0',
                    'header_slideshow' =>
                        array (
                            0 =>
                                array (
                                    'url' => '[tag_theme_uri]/assets/images/slideshow_slide1.jpg',
                                ),
                            1 =>
                                array (
                                    'url' => '[tag_theme_uri]/assets/images/slideshow_slide2.jpg',
                                ),
                        ),
                    'header_slideshow_duration' => '5000',
                    'header_slideshow_speed' => '1000',
                    'header_video_external' => 'https://www.youtube.com/watch?v=3iXYciBTQ0c',
                    'header_video_poster' => '[tag_theme_uri]/assets/images/video-poster.jpg',
                    'header_gradient' => 'plum_plate',
                    'header_show_overlay' => '1',
                    'header_overlay_type' => 'color',
                    'header_overlay_options_group_button' => '',
                    'header_overlay_color' => '#000000',
                    'header_overlay_opacity' => '0.5',
                    'header_overlay_gradient_colors' => '{"angle":"142","colors":[{"color":"rgba(244,59,71, 0.8)","position":"0%"},{"color":"rgba(69,58,148, 0.8)","position":"100%"}]}',
                    'header_overlay_shape' => 'none',
                    'header_overlay_shape_light' => '0',
                    'header_show_bottom_arrow' => '1',
                    'header_bottom_arrow_options_group_button' => '',
                    'header_bounce_bottom_arrow' => '1',
                    'header_bottom_arrow' => 'fa-angle-down',
                    'header_size_bottom_arrow' => '50',
                    'header_offset_bottom_arrow' => '20',
                    'header_color_bottom_arrow' => '#ffffff',
                    'header_background_bottom_arrow' => 'rgba(255,255,255,0)',
                    'full_height_header' => '1',
                    'header_overlap' => '0',
                    'header_overlap_with' => '200px',
                    'header_show_separator' => '0',
                    'header_options_separator_group_button' => '',
                    'header_separator' => 'mesmerize/1.wave-and-line',
                    'header_separator_color' => '#ffffff',
                    'header_separator_color_accent' => '#ff8c00',
                    'header_separator_height' => '154',
                    'header_content_show_title' => '1',
                    'header_content_title_group' => '',
                    'header_title' => 'If oportunity doesn\'t knock, build a door.',
                    'header_content_show_subtitle' => '1',
                    'header_content_subtitle_group' => '',
                    'header_subtitle' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
                    'header_content_show_buttons' => '1',
                    'header_content_buttons_group' => '',
                    'header_content_buttons' =>
                        array (
                            0 =>
                                array (
                                    'label' => 'GET STARTED TODAY',
                                    'url' => '#',
                                    'target' => '_self',
                                    'class' => 'big button color1 round',
                                ),
                            1 =>
                                array (
                                    'label' => 'LEARN MORE',
                                    'url' => '#',
                                    'target' => '_self',
                                    'class' => 'button big white round outline',
                                ),
                        ),
                    'header_content_partial' => 'content-on-center',
                    'header_content_media' => 'image',
                    'header_spacing' =>
                        array (
                            'top' => '18%',
                            'bottom' => '10%',
                        ),
                    'header_spacing_mobile' =>
                        array (
                            'top' => '10%',
                            'bottom' => '10%',
                        ),
                    'header_text_box_settings' => '',
                    'header_text_box_text_align' => 'center',
                    'header_text_box_text_width' => '70',
                    'header_text_box_text_vertical_align' => 'middle-sm',
                    'header_media_box_settings' => '',
                    'header_media_box_top_bottom_width' => '50',
                    'header_media_box_vertical_align' => 'middle-sm',
                    'header_content_image' => '[tag_theme_uri]/assets/images/headers/media-image-default.jpg',
                    'header_column_width' => '37',
                    'header_content_media_spacing' =>
                        array (
                            'top' => '0px',
                            'bottom' => '0px',
                        ),
                    'header_content_frame_type' => 'none',
                    'header_content_frame_width' => '100',
                    'header_content_frame_height' => '100',
                    'header_content_frame_offset_left' => '10',
                    'header_content_frame_offset_top' => '10',
                    'header_content_frame_thickness' => '10',
                    'header_content_frame_color' => 'rgba(0,0,0,0.5)',
                    'header_content_frame_show_over_image' => '0',
                    'header_content_frame_shadow' => '1',
                    'enable_top_bar' => '0',
                    'header_top_bar_area-left_content' => 'info',
                    'header_top_bar_area-left_info_field_0_enabled' => '1',
                    'header_top_bar_area-left_info_field_0_icon' => 'fa-map-marker',
                    'header_top_bar_area-left_info_field_0_text' => 'Location,TX 75035,USA',
                    'header_top_bar_area-left_info_field_1_enabled' => '1',
                    'header_top_bar_area-left_info_field_1_icon' => 'fa-phone',
                    'header_top_bar_area-left_info_field_1_text' => '+1234567890',
                    'header_top_bar_area-left_info_field_2_enabled' => '1',
                    'header_top_bar_area-left_info_field_2_icon' => 'fa-envelope',
                    'header_top_bar_area-left_info_field_2_text' => 'info@yourmail.com',
                    'header_top_bar_area-left_info_fields_group_button' => '',
                    'header_top_bar_area-left_social_icon_0_enabled' => '1',
                    'header_top_bar_area-left_social_icon_0_icon' => 'fa-facebook-official',
                    'header_top_bar_area-left_social_icon_0_link' => 'https://facebook.com',
                    'header_top_bar_area-left_social_icon_1_enabled' => '1',
                    'header_top_bar_area-left_social_icon_1_icon' => 'fa-twitter-square',
                    'header_top_bar_area-left_social_icon_1_link' => 'https://twitter.com',
                    'header_top_bar_area-left_social_icon_2_enabled' => '1',
                    'header_top_bar_area-left_social_icon_2_icon' => 'fa-instagram',
                    'header_top_bar_area-left_social_icon_2_link' => 'https://instagram.com',
                    'header_top_bar_area-left_social_icon_3_enabled' => '1',
                    'header_top_bar_area-left_social_icon_3_icon' => 'fa-google-plus-square',
                    'header_top_bar_area-left_social_icon_3_link' => 'https://plus.google.com',
                    'header_top_bar_area-left_social_icons_group_button' => '',
                    'header_top_bar_area-right_content' => 'social',
                    'header_top_bar_area-right_info_field_0_enabled' => '1',
                    'header_top_bar_area-right_info_field_0_icon' => 'fa-map-marker',
                    'header_top_bar_area-right_info_field_0_text' => 'Location,TX 75035,USA',
                    'header_top_bar_area-right_info_field_1_enabled' => '1',
                    'header_top_bar_area-right_info_field_1_icon' => 'fa-phone',
                    'header_top_bar_area-right_info_field_1_text' => '+1234567890',
                    'header_top_bar_area-right_info_field_2_enabled' => '1',
                    'header_top_bar_area-right_info_field_2_icon' => 'fa-envelope',
                    'header_top_bar_area-right_info_field_2_text' => 'info@yourmail.com',
                    'header_top_bar_area-right_info_fields_group_button' => '',
                    'header_top_bar_area-right_social_icon_0_enabled' => '1',
                    'header_top_bar_area-right_social_icon_0_icon' => 'fa-facebook-official',
                    'header_top_bar_area-right_social_icon_0_link' => 'https://facebook.com',
                    'header_top_bar_area-right_social_icon_1_enabled' => '1',
                    'header_top_bar_area-right_social_icon_1_icon' => 'fa-twitter-square',
                    'header_top_bar_area-right_social_icon_1_link' => 'https://twitter.com',
                    'header_top_bar_area-right_social_icon_2_enabled' => '1',
                    'header_top_bar_area-right_social_icon_2_icon' => 'fa-instagram',
                    'header_top_bar_area-right_social_icon_2_link' => 'https://instagram.com',
                    'header_top_bar_area-right_social_icon_3_enabled' => '1',
                    'header_top_bar_area-right_social_icon_3_icon' => 'fa-google-plus-square',
                    'header_top_bar_area-right_social_icon_3_link' => 'https://plus.google.com',
                    'header_top_bar_area-right_social_icons_group_button' => '',
                    'header_nav_sticked' => '1',
                    'header_nav_boxed' => '0',
                    'header_nav_border' => '1',
                    'header_nav_border_color' => 'rgba(255,255,255,0.417)',
                    'header_nav_border_thickness' => '1',
                    'header_nav_border_group_button' => '',
                    'header_nav_transparent' => '1',
                    'header_nav_use_dark_logo' => '0',
                    'header_nav_bar_type' => 'default',
                    'header_nav_style' => 'active-line-bottom',
                    'header_overlappable_section' => 'overlappable-4',
                    'one_page_express_header_image' => '[tag_theme_uri]/assets/images/home_page_header.jpg',
                ),
        ),
    'header5' =>
        array (
            'index' => 4,
            'id' => 'header_preset_4',
            'thumb' => '//extendthemes.com/assets/mesmerize/previews/headers/header5.jpg',
            'preview' => '//extendthemes.com/assets/mesmerize/previews/headers/header5.jpg',
            'description' => 'header preset 5',
            'settings' =>
                array (
                    'header_text' => '1',
                    'header_textcolor' => '',
                    'header_video' => '',
                    'external_header_video' => '',
                    'header_image' => '[tag_theme_uri]/assets/images/headers/home_page_header.jpg',
                    'header_image_data' => '',
                    'header_presets' => '',
                    'frontpage_header_presets_pro' => '',
                    'header_offscreen_nav_on_tablet' => '0',
                    'header_offscreen_nav_on_desktop' => '0',
                    'header_background_type' => 'image',
                    'header_bg_options_group_button' => '',
                    'header_bg_color' => '#6a73da',
                    'header_front_page_image' => '[tag_theme_uri]/assets/images/headers/pixabay-girl-2618562.jpg',
                    'header_parallax_pro' => '',
                    'header_bg_position' => 'center bottom',
                    'header_parallax' => '1',
                    'header_front_page_image_mobile' => '',
                    'header_bg_position_mobile' => '50%',
                    'header_bg_position_mobile_offset' => '0',
                    'header_slideshow' =>
                        array (
                            0 =>
                                array (
                                    'url' => '[tag_theme_uri]/assets/images/slideshow_slide1.jpg',
                                ),
                            1 =>
                                array (
                                    'url' => '[tag_theme_uri]/assets/images/slideshow_slide2.jpg',
                                ),
                        ),
                    'header_slideshow_duration' => '5000',
                    'header_slideshow_speed' => '1000',
                    'header_video_external' => 'https://www.youtube.com/watch?v=3iXYciBTQ0c',
                    'header_video_poster' => '[tag_theme_uri]/assets/images/video-poster.jpg',
                    'header_gradient' => 'plum_plate',
                    'header_show_overlay' => '1',
                    'header_overlay_type' => 'color',
                    'header_overlay_options_group_button' => '',
                    'header_overlay_color' => '#000000',
                    'header_overlay_opacity' => '0.5',
                    'header_overlay_gradient_colors' => '{"angle":"142","colors":[{"color":"rgba(244,59,71, 0.8)","position":"0%"},{"color":"rgba(69,58,148, 0.8)","position":"100%"}]}',
                    'header_overlay_shape' => 'none',
                    'header_overlay_shape_light' => '0',
                    'header_show_bottom_arrow' => '0',
                    'header_bottom_arrow_options_group_button' => '',
                    'header_bounce_bottom_arrow' => '1',
                    'header_bottom_arrow' => 'fa-angle-down',
                    'header_size_bottom_arrow' => '50',
                    'header_offset_bottom_arrow' => '20',
                    'header_color_bottom_arrow' => '#ffffff',
                    'header_background_bottom_arrow' => 'rgba(255,255,255,0)',
                    'full_height_header' => '0',
                    'header_overlap' => '0',
                    'header_overlap_with' => '200px',
                    'header_show_separator' => '0',
                    'header_options_separator_group_button' => '',
                    'header_separator' => 'mesmerize/1.wave-and-line',
                    'header_separator_color' => '#ffffff',
                    'header_separator_color_accent' => '#ff8c00',
                    'header_separator_height' => '154',
                    'header_content_show_title' => '1',
                    'header_content_title_group' => '',
                    'header_title' => 'If oportunity doesn\'t knock, build a door',
                    'header_content_show_subtitle' => '1',
                    'header_content_subtitle_group' => '',
                    'header_subtitle' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
                    'header_content_show_buttons' => '1',
                    'header_content_buttons_group' => '',
                    'header_content_buttons' =>
                        array (
                            0 =>
                                array (
                                    'label' => 'GET STARTED TODAY',
                                    'url' => '#',
                                    'target' => '_self',
                                    'class' => 'big button color1 round',
                                ),
                            1 =>
                                array (
                                    'label' => 'LEARN MORE',
                                    'url' => '#',
                                    'target' => '_self',
                                    'class' => 'button big white round outline',
                                ),
                        ),
                    'header_content_partial' => 'content-on-left',
                    'header_content_media' => 'image',
                    'header_spacing' =>
                        array (
                            'top' => '15%',
                            'bottom' => '15%',
                        ),
                    'header_spacing_mobile' =>
                        array (
                            'top' => '10%',
                            'bottom' => '10%',
                        ),
                    'header_text_box_settings' => '',
                    'header_text_box_text_align' => 'left',
                    'header_text_box_text_width' => '50',
                    'header_text_box_text_vertical_align' => 'middle-sm',
                    'header_media_box_settings' => '',
                    'header_media_box_top_bottom_width' => '50',
                    'header_media_box_vertical_align' => 'middle-sm',
                    'header_content_image' => '[tag_theme_uri]/assets/images/headers/media-image-default.jpg',
                    'header_column_width' => '37',
                    'header_content_media_spacing' =>
                        array (
                            'top' => '0px',
                            'bottom' => '0px',
                        ),
                    'header_content_frame_type' => 'none',
                    'header_content_frame_width' => '100',
                    'header_content_frame_height' => '100',
                    'header_content_frame_offset_left' => '10',
                    'header_content_frame_offset_top' => '10',
                    'header_content_frame_thickness' => '10',
                    'header_content_frame_color' => 'rgba(0,0,0,0.5)',
                    'header_content_frame_show_over_image' => '0',
                    'header_content_frame_shadow' => '1',
                    'enable_top_bar' => '1',
                    'header_top_bar_area-left_content' => 'info',
                    'header_top_bar_area-left_info_field_0_enabled' => '1',
                    'header_top_bar_area-left_info_field_0_icon' => 'fa-map-marker',
                    'header_top_bar_area-left_info_field_0_text' => 'Location,TX 75035,USA',
                    'header_top_bar_area-left_info_field_1_enabled' => '1',
                    'header_top_bar_area-left_info_field_1_icon' => 'fa-phone',
                    'header_top_bar_area-left_info_field_1_text' => '+1234567890',
                    'header_top_bar_area-left_info_field_2_enabled' => '1',
                    'header_top_bar_area-left_info_field_2_icon' => 'fa-envelope',
                    'header_top_bar_area-left_info_field_2_text' => 'info@yourmail.com',
                    'header_top_bar_area-left_info_fields_group_button' => '',
                    'header_top_bar_area-left_social_icon_0_enabled' => '1',
                    'header_top_bar_area-left_social_icon_0_icon' => 'fa-facebook-official',
                    'header_top_bar_area-left_social_icon_0_link' => 'https://facebook.com',
                    'header_top_bar_area-left_social_icon_1_enabled' => '1',
                    'header_top_bar_area-left_social_icon_1_icon' => 'fa-twitter-square',
                    'header_top_bar_area-left_social_icon_1_link' => 'https://twitter.com',
                    'header_top_bar_area-left_social_icon_2_enabled' => '1',
                    'header_top_bar_area-left_social_icon_2_icon' => 'fa-instagram',
                    'header_top_bar_area-left_social_icon_2_link' => 'https://instagram.com',
                    'header_top_bar_area-left_social_icon_3_enabled' => '1',
                    'header_top_bar_area-left_social_icon_3_icon' => 'fa-google-plus-square',
                    'header_top_bar_area-left_social_icon_3_link' => 'https://plus.google.com',
                    'header_top_bar_area-left_social_icons_group_button' => '',
                    'header_top_bar_area-right_content' => 'social',
                    'header_top_bar_area-right_info_field_0_enabled' => '1',
                    'header_top_bar_area-right_info_field_0_icon' => 'fa-map-marker',
                    'header_top_bar_area-right_info_field_0_text' => 'Location,TX 75035,USA',
                    'header_top_bar_area-right_info_field_1_enabled' => '1',
                    'header_top_bar_area-right_info_field_1_icon' => 'fa-phone',
                    'header_top_bar_area-right_info_field_1_text' => '+1234567890',
                    'header_top_bar_area-right_info_field_2_enabled' => '1',
                    'header_top_bar_area-right_info_field_2_icon' => 'fa-envelope',
                    'header_top_bar_area-right_info_field_2_text' => 'info@yourmail.com',
                    'header_top_bar_area-right_info_fields_group_button' => '',
                    'header_top_bar_area-right_social_icon_0_enabled' => '1',
                    'header_top_bar_area-right_social_icon_0_icon' => 'fa-facebook-official',
                    'header_top_bar_area-right_social_icon_0_link' => 'https://facebook.com',
                    'header_top_bar_area-right_social_icon_1_enabled' => '1',
                    'header_top_bar_area-right_social_icon_1_icon' => 'fa-twitter-square',
                    'header_top_bar_area-right_social_icon_1_link' => 'https://twitter.com',
                    'header_top_bar_area-right_social_icon_2_enabled' => '1',
                    'header_top_bar_area-right_social_icon_2_icon' => 'fa-instagram',
                    'header_top_bar_area-right_social_icon_2_link' => 'https://instagram.com',
                    'header_top_bar_area-right_social_icon_3_enabled' => '1',
                    'header_top_bar_area-right_social_icon_3_icon' => 'fa-google-plus-square',
                    'header_top_bar_area-right_social_icon_3_link' => 'https://plus.google.com',
                    'header_top_bar_area-right_social_icons_group_button' => '',
                    'header_nav_sticked' => '1',
                    'header_nav_boxed' => '0',
                    'header_nav_border' => '0',
                    'header_nav_border_color' => 'rgba(255, 255, 255, 1)',
                    'header_nav_border_thickness' => '2',
                    'header_nav_border_group_button' => '',
                    'header_nav_transparent' => '0',
                    'header_nav_use_dark_logo' => '0',
                    'header_nav_bar_type' => 'default',
                    'header_nav_style' => 'active-line-bottom',
                    'one_page_express_header_image' => '[tag_theme_uri]/assets/images/home_page_header.jpg',
                ),
        ),
);

